# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/shopping-mall?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: heyuxin
  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379
#  password: 1234
  servlet:
    multipart:
      max-file-size: 10MB

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml



shopping-mall:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateCaptcha
  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: shopping-mall