server:
  port: 8512

spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/shopping-mall?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: heyuxin
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml

shopping-mall:
  sms:
    appcode: 938a8491cea74e43a48edf0a67070051
    host: https://dfsns.market.alicloudapi.com
    path: /data/send_sms